# Generated by Django 5.2.7 on 2025-10-28 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Case Categories',
                'db_table': 'case_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CasePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('level', models.IntegerField(unique=True)),
                ('color_code', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Case Priorities',
                'db_table': 'case_priorities',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='CaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_code', models.CharField(default='#000000', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Case Statuses',
                'db_table': 'case_statuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaseTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
            ],
            options={
                'db_table': 'case_tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('opposing_party', models.CharField(blank=True, max_length=300)),
                ('opposing_lawyer', models.CharField(blank=True, max_length=300)),
                ('filing_date', models.DateField()),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('next_hearing_date', models.DateField(blank=True, db_index=True, null=True)),
                ('expected_closure_date', models.DateField(blank=True, null=True)),
                ('actual_closure_date', models.DateField(blank=True, null=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fees_charged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal notes - not visible to customer')),
                ('assigned_lawyer', models.ForeignKey(help_text='Primary lawyer handling the case', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='base.court')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='customers.customer')),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='base.judge')),
                ('team_members', models.ManyToManyField(blank=True, help_text='Additional team members', related_name='team_cases', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casecategory')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casepriority')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casestatus')),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('document_type', models.CharField(choices=[('petition', 'Petition'), ('evidence', 'Evidence'), ('affidavit', 'Affidavit'), ('order', 'Court Order'), ('judgment', 'Judgment'), ('notice', 'Notice'), ('contract', 'Contract'), ('misc', 'Miscellaneous')], default='misc', max_length=100)),
                ('file', models.FileField(upload_to='case_documents/%Y/%m/')),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('is_visible_to_customer', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_documents', to='cases.case')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTagRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='cases.case')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_relations', to='cases.casetag')),
            ],
            options={
                'db_table': 'case_tag_relations',
            },
        ),
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('update_type', models.CharField(choices=[('hearing', 'Hearing'), ('document', 'Document Filed'), ('judgment', 'Judgment'), ('motion', 'Motion Filed'), ('note', 'General Note'), ('status_change', 'Status Change')], default='note', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible_to_customer', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'case_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_date', models.DateTimeField()),
                ('hearing_type', models.CharField(choices=[('first_hearing', 'First Hearing'), ('evidence', 'Evidence Hearing'), ('arguments', 'Arguments'), ('final', 'Final Hearing'), ('misc', 'Miscellaneous')], default='misc', max_length=100)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('agenda', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Notes taken during hearing')),
                ('outcome', models.TextField(blank=True)),
                ('next_hearing_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=50)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.judge')),
            ],
            options={
                'db_table': 'hearings',
                'ordering': ['hearing_date'],
            },
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='cases_case_nu_25894f_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'priority'], name='cases_status__1891c8_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['next_hearing_date'], name='cases_next_he_277234_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['customer', 'is_active'], name='cases_custome_4537c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casetagrelation',
            unique_together={('case', 'tag')},
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['hearing_date', 'status'], name='hearings_hearing_30a83f_idx'),
        ),
    ]
