# Generated by Django 5.2.7 on 2025-10-29 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('courts', '0002_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_lawyer',
            field=models.ForeignKey(help_text='Primary lawyer handling the case', on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='courts.court'),
        ),
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='case',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='courts.judge'),
        ),
        migrations.AddField(
            model_name='case',
            name='team_members',
            field=models.ManyToManyField(blank=True, help_text='Additional team members', related_name='team_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casecategory'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_documents', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casedocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casepriority'),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='cases.casestatus'),
        ),
        migrations.AddField(
            model_name='casetagrelation',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casetagrelation',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_relations', to='cases.case'),
        ),
        migrations.AddField(
            model_name='casetagrelation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_relations', to='cases.casetag'),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cases.case'),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hearing',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearings', to='cases.case'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hearing',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.judge'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='cases_case_nu_25894f_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'priority'], name='cases_status__1891c8_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['next_hearing_date'], name='cases_next_he_277234_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['customer', 'is_active'], name='cases_custome_4537c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='casetagrelation',
            unique_together={('case', 'tag')},
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['hearing_date', 'status'], name='hearings_hearing_30a83f_idx'),
        ),
    ]
