# Generated by Django 5.2.7 on 2025-10-29 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('resume', 'Resume/CV'), ('certificate', 'Certificate'), ('id_proof', 'ID Proof'), ('agreement', 'Agreement'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'employee_documents',
            },
        ),
        migrations.CreateModel(
            name='PermissionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permissions', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'permission_sets',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(choices=[('lawyer', 'Lawyer'), ('paralegal', 'Paralegal'), ('clerk', 'Clerk'), ('manager', 'Manager'), ('admin', 'Admin')], max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('bar_registration_number', models.CharField(blank=True, max_length=100)),
                ('date_of_joining', models.DateField()),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
                ('custom_permissions', models.JSONField(blank=True, default=dict)),
                ('address', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='courts.court')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
